// Generated by CoffeeScript 1.10.0
(function() {
  var InvalidAccess, LoginError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  LoginError = (function(superClass) {
    extend(LoginError, superClass);

    function LoginError(message) {
      this.message = message != null ? message : "用户名或密码错误";
      this.name = 'LoginError';
      this.status = 401;
      Error.captureStackTrace(this, LoginError);
    }

    return LoginError;

  })(Error);

  InvalidAccess = (function(superClass) {
    extend(InvalidAccess, superClass);

    function InvalidAccess(message) {
      this.message = message != null ? message : "需要登录";
      this.name = 'InvalidAccess';
      this.status = 403;
      Error.captureStackTrace(this, InvalidAccess);
    }

    return InvalidAccess;

  })(Error);

  module.exports = {
    LoginError: LoginError,
    InvalidAccess: InvalidAccess
  };

}).call(this);

//# sourceMappingURL=errors.js.map
