// Generated by CoffeeScript 1.10.0
(function() {
  var passwordHash;

  passwordHash = require('password-hash');

  console.log(passwordHash.generate("hcpoc"));

}).call(this);

//# sourceMappingURL=generatePW.js.map
