// Generated by CoffeeScript 1.10.0
(function() {
  var Errors, db, express, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  db = require('../database');

  Errors = require('../errors');

  router.get('/', function(req, res) {
    var News;
    News = db.models.news;
    return News.findAll().then(function(news_list) {
      var news;
      news_list = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = news_list.length; i < len; i++) {
          news = news_list[i];
          results.push(news.get({
            plain: true
          }));
        }
        return results;
      })();
      return res.json(news_list);
    })["catch"](function(err) {
      res.status(err.status || 400);
      return res.json(err);
    });
  }).get('/:news_id', function(req, res) {
    var News;
    News = db.models.news;
    return News.find(req.params.news_id).then(function(news) {
      if (!news) {
        throw new Errors.InvalidAccess("Cannot find this piece of news.");
      }
      return res.json(news.get({
        plain: true
      }));
    })["catch"](function(err) {
      res.status(err.status || 400);
      return res.json(err);
    });
  }).use(function(req, res, next) {
    var err, ref, ref1;
    if ((req != null ? (ref = req.session) != null ? (ref1 = ref.user) != null ? ref1.id : void 0 : void 0 : void 0) !== 0) {
      err = new Errors.InvalidAccess();
      console.log(err);
      res.status(err.status || 400);
      return res.json(err);
    } else {
      return next(req, res);
    }
  }).post('/', function(req, res) {
    var News;
    News = db.models.news;
    console.log(req.body);
    return News.create({
      title: req.body.title,
      content: req.body.content
    }).then(function(news) {
      console.log(news.get({
        plain: true
      }));
      return res.json(news.get({
        plain: true
      }));
    })["catch"](function(err) {
      res.status(err.status || 400);
      return res.json(err);
    });
  }).post('/:news_id', function(req, res) {
    var News;
    News = db.models.news;
    return News.find(req.params.news_id).then(function(news) {
      if (!news) {
        throw new Errors.InvalidAccess("Cannot find this piece of news.");
      }
      news.title = req.body.title;
      news.content = req.body.content;
      return news.save();
    }).then(function(news) {
      return res.json(news.get({
        plain: true
      }));
    })["catch"](function(err) {
      res.status(err.status || 400);
      return res.json(err);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=news.js.map
