// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('richtext', {
      name: {
        type: DataTypes.STRING,
        unique: true,
        allowNull: false
      },
      content: {
        type: DataTypes.TEXT('long')
      },
      access_level: {
        type: DataTypes.ENUM('private', 'protect', 'public'),
        defaultValue: 'public'
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=richtext.js.map
